# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

source 'git@github.com:ModularizationDemo/PodSpec.git'
source 'https://github.com/CocoaPods/Specs.git'

target '__ProjectName__' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Lothar', '~> 1.0.3' 
end
