# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

source 'git@github.com:ModularizationDemo/PodSpec.git'
source 'https://github.com/CocoaPods/Specs.git'

target '__ProjectName__' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'ReactiveCocoa','2.5'
  pod 'HLNetworking', '~> 2.0'
  pod 'MJExtension', '~> 2.0'
  pod 'SDWebImage','~> 3.7'
end
